"""
Helper utilities for the finance advisor
"""

import logging
import logging.config
import yaml
from datetime import datetime
from pathlib import Path
from typing import Dict, Any

PROJECT_ROOT = Path(__file__).resolve().parents[2]

def _resolve_config_path(config_path):
    """Resolve logging config paths relative to the project root."""
    path = Path(config_path)
    if path.is_absolute():
        return path

    for base in [PROJECT_ROOT, Path.cwd()]:
        candidate = base / path
        if candidate.exists():
            return candidate

    return PROJECT_ROOT / path


def setup_logging(config_path='config/logging_config.yaml'):
    """Setup logging configuration"""
    try:
        resolved_path = _resolve_config_path(config_path)
        with open(resolved_path, 'r', encoding='utf-8') as f:
            config = yaml.safe_load(f)
        
        logging.config.dictConfig(config)
        return logging.getLogger(__name__)
    except Exception:
        # Fallback basic logging
        logging.basicConfig(
            level=logging.INFO,
            format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
        )
        return logging.getLogger(__name__)

def format_currency(amount):
    """Format amount as currency"""
    return f"${amount:,.2f}"

def calculate_financial_ratios(user_data):
    """Calculate key financial ratios"""
    income = user_data.get('income', 0)
    expenses = user_data.get('expenses', 0)
    savings = user_data.get('savings', 0)
    debt = user_data.get('debt', 0)
    
    if income > 0:
        ratios = {
            'savings_rate': savings / income,
            'expense_rate': expenses / income,
            'debt_to_income': debt / income,
            'disposable_income': income - expenses
        }
    else:
        ratios = {
            'savings_rate': 0,
            'expense_rate': 0,
            'debt_to_income': 0,
            'disposable_income': 0
        }
    
    return ratios

def generate_report_summary(classification_result, user_data):
    """Generate a human-readable summary report"""
    summary = []
    
    # Header
    summary.append("=" * 60)
    summary.append("FINANCIAL BEHAVIOR ANALYSIS REPORT")
    summary.append("=" * 60)
    
    # User info
    summary.append(f"User ID: {user_data.get('user_id', 'N/A')}")
    summary.append(f"Analysis Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    summary.append("")
    
    # Classification
    summary.append("Behavior Classification:")
    summary.append(f"  • Category: {classification_result.get('behavior', 'unknown').upper()}")
    summary.append(f"  • Score: {classification_result.get('score', 0):.1f}/100")
    summary.append(f"  • Confidence: {classification_result.get('rule_confidence', 0):.2%}")
    summary.append("")
    
    # Financial metrics
    ratios = calculate_financial_ratios(user_data)
    summary.append("Key Financial Metrics:")
    summary.append(f"  • Savings Rate: {ratios['savings_rate']:.1%}")
    summary.append(f"  • Expense Rate: {ratios['expense_rate']:.1%}")
    summary.append(f"  • Debt-to-Income: {ratios['debt_to_income']:.1%}")
    summary.append(f"  • Disposable Income: {format_currency(ratios['disposable_income'])}")
    summary.append("")
    
    # Recommendations
    strategies = classification_result.get('strategies', ['budget_planning'])
    summary.append("Recommended Strategies:")
    for i, strategy in enumerate(strategies, 1):
        summary.append(f"  {i}. {strategy.replace('_', ' ').title()}")
    summary.append("")
    
    # Footer
    summary.append("=" * 60)
    summary.append("Generated by Personal Finance Advisor System")
    summary.append("=" * 60)
    
    return "\n".join(summary)